version: '3'

# Local volumes for services to persist the data even if the container is destroyed or recreated.
volumes:
  pg_data:
    driver: local
  redis:
    driver: local

# Custom x-attribute with common settings for backend service.
x-base: &base-backend
  env_file:
    - .env
  volumes:
    - .:/store:delegated
  depends_on:
    - db
    - redis

services:
  redis:
    image: library/redis:6.0
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  backend:
    <<: *base-backend
    build: .
    image: store/backend:1.0.0
    ports:
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    <<: *base-backend
    build: .
    command: celery -A apps.celery_app worker -l INFO -Q default

  beat:
    <<: *base-backend
    build: .
    command: celery -A apps.celery_app beat -l INFO -s /var/run/celerybeat-schedule --pidfile /var/run/celerybeat.pid
